const quuestion = [
  {
    id: 1,
    title: "How do I use React Context?",
    tags: ["React", "JavaScript"],
    votes: 10,
    answers: 3,
    createdAt: "2024-12-01T12:00:00Z",
  },
  {
    id: 2,
    title: "What is the best way to optimize MySQL queries?",
    tags: ["SQL", "MySQL"],
    votes: 7,
    answers: 2,
    createdAt: "2024-12-01T15:00:00Z",
  },
  {
    id: 2,
    title: "What is the best way to optimize MySQL queries?",
    tags: ["SQL", "MySQL"],
    votes: 7,
    answers: 2,
    createdAt: "2024-12-01T15:00:00Z",
  },
  {
    id: 2,
    title: "What is the best way to optimize MySQL queries?",
    tags: ["SQL", "MySQL"],
    votes: 7,
    answers: 2,
    createdAt: "2024-12-01T15:00:00Z",
  },
  {
    id: 2,
    title: "What is the best way to optimize MySQL queries?",
    tags: ["SQL", "MySQL"],
    votes: 7,
    answers: 2,
    createdAt: "2024-12-01T15:00:00Z",
  },
  {
    id: 2,
    title: "What is the best way to optimize MySQL queries?",
    tags: ["SQL", "MySQL"],
    votes: 7,
    answers: 2,
    createdAt: "2024-12-01T15:00:00Z",
  },
  {
    id: 2,
    title: "What is the best way to optimize MySQL queries?",
    tags: ["SQL", "MySQL"],
    votes: 7,
    answers: 2,
    createdAt: "2024-12-01T15:00:00Z",
  },
];
export default quuestion